### Get all employees
GET {{host}}/api/v1/employees

### Create new employee
POST {{host}}/api/v1/employees
Content-Type: application/json

{
  "firstName": "Angel",
  "lastName": "Cruz",
  "email": "me@angelcruzl.dev"
}

### Get employee by id
GET {{host}}/api/v1/employees/663829870f1b7f389936368f
